import React from "react";
import styled from "@emotion/styled";
/**
 * `<Row>` ('row')
 * - [Open in Figma](https://figma.com/file/1FTzSY1Y0v5oLlpOkNYsQj?node-id=236:11778)
 * - [Open in Grida](https://code.grida.co/files/1FTzSY1Y0v5oLlpOkNYsQj?node=236:11778)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <Row/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/921a9114-6fbc-4ead-9b45-b36235e4cadd)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://1FTzSY1Y0v5oLlpOkNYsQj/236:11778 -->
 */
export function Footer() {
    return (
        <RootWrapperRow>
            <Frame197>
                <ColMd3>
                    <Frame198>
                        <NaN_0001>
                            Строй Дом Маркет
                        </NaN_0001>
                        <Paragraph>
                            Интернет магазин инструментов
                        </Paragraph>
                    </Frame198>
                    <SocialMedia>
                        <Facebook src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/cde5fc0c-627b-44e4-a7de-71bc23343093" alt="icon"/>
                        <Instagram src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/924b576f-799e-468c-a7b0-c5f4c1b2155b" alt="icon"/>
                        <Twitter>
                            <AntDesignTwitterOutlined>
                                <Vector xmlns="http://www.w3.org/2000/svg">
                                    <path fill="white" d="M6.91075 18C15.213 18 19.7546 11.0731 19.7546 5.07669C19.7546 4.88285 19.7546 4.68625 19.7464 4.49241C20.6306 3.84789 21.3937 3.04993 22 2.13592C21.1741 2.50262 20.2988 2.7443 19.4026 2.85312C20.3466 2.28495 21.0536 1.391 21.3923 0.337403C20.5054 0.86647 19.5346 1.23787 18.5226 1.43534C17.8423 0.705724 16.9419 0.222372 15.9611 0.0601592C14.9803 -0.102054 13.9737 0.0659244 13.0973 0.538075C12.2209 1.01023 11.5236 1.7602 11.1134 2.67182C10.7031 3.58345 10.6029 4.60585 10.8281 5.58066C9.03339 5.49005 7.27762 5.02057 5.67468 4.20269C4.07175 3.3848 2.65744 2.23678 1.5235 0.833069C0.947843 1.83421 0.772164 3.01843 1.03214 4.14526C1.29211 5.27209 1.96825 6.25705 2.92325 6.90013C2.20762 6.87565 1.50772 6.68215 0.88 6.33524L0.88 6.39754C0.881234 7.44631 1.24205 8.46247 1.90145 9.27429C2.56086 10.0861 3.4784 10.6438 4.499 10.853C4.11161 10.9605 3.71144 11.014 3.30963 11.0122C3.02635 11.0131 2.74365 10.9867 2.46537 10.9333C2.75383 11.8361 3.3155 12.6254 4.07171 13.1908C4.82793 13.7561 5.74081 14.0691 6.6825 14.0859C5.08276 15.3511 3.10668 16.0373 1.0725 16.034C0.714066 16.0355 0.355882 16.0147 0 15.9716C2.06458 17.297 4.46228 18.0008 6.91075 18L6.91075 18Z"/>
                                </Vector>
                            </AntDesignTwitterOutlined>
                        </Twitter>
                    </SocialMedia>
                </ColMd3>
                <Frame195>
                    <Frame196>
                        <ScheduleFill0Wght300Grad0Opsz2411 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2ab87fb3-a615-43c4-b3e3-1e47f3acea04" alt="icon"/>
                        <_90020009001700>
                            Пн.-Сб.: 9:00-20:00, Вс.: 9:00-17:00
                        </_90020009001700>
                    </Frame196>
                    <BtnSm20>
                        <CallFill0Wght300Grad0Opsz241 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/83ab7aad-37de-44da-8cf3-be0da524b4be" alt="icon"/>
                        <H6>
                            +7(909) 623-22-33
                        </H6>
                    </BtnSm20>
                    <Info>
                        <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/813a67fa-1403-48ee-ad56-485fe28cdf30" alt="icon"/>
                        <H6>
                            Москва
                        </H6>
                    </Info>
                    <Info>
                        <MailFill0Wght300Grad0Opsz241 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7d075a99-f703-4703-8d1b-75d1f3d07f5d" alt="icon"/>
                        <H6>
                            электронная почта
                        </H6>
                    </Info>
                </Frame195>
            </Frame197>
            <Container>
                <Row_0001>
                    <ColMd6>
                        <_20062023>
                            © 2006–2023. Все права защищены.
                        </_20062023>
                    </ColMd6>
                </Row_0001>
            </Container>
        </RootWrapperRow>
    )
}

const RootWrapperRow = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	gap: 24px;
	background: rgb(42, 124, 199);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 30px 60px 0px;
`;

const Frame197 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 8px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const ColMd3 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame198 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 8px;
	box-sizing: border-box;
`;

const NaN_0001 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Montserrat, sans-serif;
	font-weight: 800;
	text-align: left;
`;

const Paragraph = styled.span`
	color: rgba(255, 255, 255, 0.7);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

const SocialMedia = styled.div`
	display: flex;
	justify-content: flex-end;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 20px;
	width: 1057px;
	box-sizing: border-box;
`;

const Facebook = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Instagram = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Twitter = styled.div`
	width: 24px;
	height: 20px;
	overflow: hidden;
	position: relative;
`;

const AntDesignTwitterOutlined = styled.div`
	width: 24px;
	height: 20px;
	overflow: hidden;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Vector = styled.svg`
	width: 22px;
	height: 18px;
	position: absolute;
	left: 2px;
	top: 1px;
	right: 1px;
	bottom: 1px;
`;

const Frame195 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 50px;
	box-sizing: border-box;
`;

const Frame196 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	box-sizing: border-box;
`;

const ScheduleFill0Wght300Grad0Opsz2411 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const _90020009001700 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	text-align: center;
`;

const BtnSm20 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	border-radius: 5px;
	box-sizing: border-box;
`;

const CallFill0Wght300Grad0Opsz241 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const H6 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	text-align: center;
`;

const Info = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	border-radius: 4px;
	box-sizing: border-box;
	padding: 2px 0px;
`;

const Icon = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const MailFill0Wght300Grad0Opsz241 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Container = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	width: 1050px;
	box-sizing: border-box;
	padding: 25px 0px;
`;

const Row_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 213px;
	box-sizing: border-box;
`;

const ColMd6 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	width: 513px;
	box-sizing: border-box;
`;

const _20062023 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

