import React from "react";
import styled from "@emotion/styled";
/**
 * `<HomepageCategory>` ('Homepage & Category')
 * - [Open in Figma](https://figma.com/file/1FTzSY1Y0v5oLlpOkNYsQj?node-id=32:992)
 * - [Open in Grida](https://code.grida.co/files/1FTzSY1Y0v5oLlpOkNYsQj?node=32:992)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <HomepageCategory/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8064f5b3-0991-42aa-ac00-beb77a3955af)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://1FTzSY1Y0v5oLlpOkNYsQj/32:992 -->
 */
export function HomepageCategory() {
    return (
        <RootWrapperHomepageCategory>
            <NavbarStyle8NavbarLight>
                <Container>
                    <Row>
                        <ColMd4>
                            <Button>
                                <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/79a34b5e-9f4d-457e-b7b1-c3eb73d6ef3b" alt="icon"/>
                                <H6>
                                    Москва
                                </H6>
                            </Button>
                            <BtnSm20>
                                <IcnSettingsIcnXs src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e5722d5a-a252-44d5-bccd-d116465835a3" alt="icon"/>
                                <H6_0001>
                                    +7(909) 623-22-33
                                </H6_0001>
                            </BtnSm20>
                        </ColMd4>
                        <ColMd4_0001>
                            <NaN_0001>
                                Интернет магазин инструментов
                            </NaN_0001>
                        </ColMd4_0001>
                        <Left>
                            <Button_0001>
                                <H6>
                                    Контакты
                                </H6>
                            </Button_0001>
                        </Left>
                    </Row>
                </Container>
                <Frame15>
                    <_4>
                        <Frame13>
                            <Logo>
                                <NaN_0002>
                                    Строй Дом Маркет
                                </NaN_0002>
                            </Logo>
                            <InputHeader>
                                <Button_0002>
                                    <H6_0003>
                                        Все
                                    </H6_0003>
                                    <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c05b1e8d-9e4b-472a-908e-e30416f46811" alt="icon"/>
                                </Button_0002>
                                <NaN_0003>
                                    Поиск
                                </NaN_0003>
                            </InputHeader>
                            <Frame11>
                                <Button_0003>
                                    <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/98f51604-c71e-4467-960c-2e80e086fdbe" alt="icon"/>
                                    <H6_0004>
                                        Войти
                                    </H6_0004>
                                </Button_0003>
                                <Button_0004>
                                    <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e87beca5-b605-4dcb-8e74-b29828756e04" alt="icon"/>
                                    <H6_0004>
                                        Корзина
                                    </H6_0004>
                                    <Badge>
                                        <Text>
                                            1
                                        </Text>
                                    </Badge>
                                </Button_0004>
                            </Frame11>
                        </Frame13>
                    </_4>
                    <_2>
                        <Button_0005>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ddbff8a1-8ff8-4325-beed-b400705467ec" alt="icon"/>
                            <H6_0006>
                                Каталог товаров
                            </H6_0006>
                        </Button_0005>
                        <Frame14>
                            <Tab>
                                <Text_0001>
                                    Стройкa
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Сад и досуг
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Техника
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Все для дома
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Кухня
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Ванная комната
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Строительное оборудование
                                </Text_0001>
                            </Tab>
                        </Frame14>
                    </_2>
                </Frame15>
            </NavbarStyle8NavbarLight>
            <Banner>
                <ButtonNext>
                    <Vector xmlns="http://www.w3.org/2000/svg">
                        <path fill="white" d="M0.500773 0.497901C0.659111 0.340073 0.847209 0.214854 1.0543 0.129417C1.26138 0.0439786 1.48339 0 1.70759 0C1.9318 0 2.1538 0.0439786 2.36089 0.129417C2.56797 0.214854 2.75607 0.340073 2.91441 0.497901L23.369 20.8351C23.5277 20.9925 23.6536 21.1795 23.7396 21.3854C23.8255 21.5913 23.8697 21.812 23.8697 22.035C23.8697 22.2579 23.8255 22.4786 23.7396 22.6845C23.6536 22.8904 23.5277 23.0774 23.369 23.2348L2.91441 43.572C2.59434 43.8902 2.16024 44.069 1.70759 44.069C1.25495 44.069 0.820841 43.8902 0.500773 43.572C0.180705 43.2538 0.000892444 42.8222 0.000892444 42.3721C0.000892444 41.9221 0.180705 41.4905 0.500773 41.1722L19.7519 22.035L0.500773 2.89769C0.342035 2.74026 0.216093 2.55324 0.130162 2.34734C0.0442308 2.14144 0 1.92071 0 1.69779C0 1.47487 0.0442308 1.25414 0.130162 1.04825C0.216093 0.842349 0.342035 0.65533 0.500773 0.497901L0.500773 0.497901Z"/>
                    </Vector>
                </ButtonNext>
                <ButtonPrevious>
                    <Vector xmlns="http://www.w3.org/2000/svg">
                        <path fill="white" d="M0.500773 0.497901C0.659111 0.340073 0.847209 0.214854 1.0543 0.129417C1.26138 0.0439786 1.48339 0 1.70759 0C1.9318 0 2.1538 0.0439786 2.36089 0.129417C2.56797 0.214854 2.75607 0.340073 2.91441 0.497901L23.369 20.8351C23.5277 20.9925 23.6536 21.1795 23.7396 21.3854C23.8255 21.5913 23.8697 21.812 23.8697 22.035C23.8697 22.2579 23.8255 22.4786 23.7396 22.6845C23.6536 22.8904 23.5277 23.0774 23.369 23.2348L2.91441 43.572C2.59434 43.8902 2.16024 44.069 1.70759 44.069C1.25495 44.069 0.820841 43.8902 0.500773 43.572C0.180705 43.2538 0.000892444 42.8222 0.000892444 42.3721C0.000892444 41.9221 0.180705 41.4905 0.500773 41.1722L19.7519 22.035L0.500773 2.89769C0.342035 2.74026 0.216093 2.55324 0.130162 2.34734C0.0442308 2.14144 0 1.92071 0 1.69779C0 1.47487 0.0442308 1.25414 0.130162 1.04825C0.216093 0.842349 0.342035 0.65533 0.500773 0.497901L0.500773 0.497901Z"/>
                    </Vector>
                </ButtonPrevious>
                <Pagination>
                    <Lines/>
                    <Lines_0001/>
                    <Lines_0001/>
                    <Lines_0001/>
                </Pagination>
            </Banner>
            <Frame30>
                <Frame18>
                    <Title>
                        <NaN_0004>
                            Новинки
                        </NaN_0004>
                    </Title>
                    <Frame18_0001>
                        <Frame16>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0e2fb1f7-c744-475b-a4c8-26142d3dfbb3" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/24364a60-537a-49b0-b4b6-4cc427c2d685" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/99b0da0a-c32d-4854-9f48-8c7459bb39d6" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/91d18bb1-31ae-4b86-91f6-324b6edf7ca4" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/af48fd11-b845-4f9b-a593-5ad723899e14" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                        </Frame16>
                        <Button_0011>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/46ecb8e5-4d99-46e6-977b-ae8c474ed49f" alt="icon"/>
                        </Button_0011>
                        <Button_0012>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8372463b-06a7-4ce1-b565-ab7b0c0a2025" alt="icon"/>
                        </Button_0012>
                    </Frame18_0001>
                </Frame18>
                <Frame29>
                    <Frame19>
                        <Title_0006>
                            <NaN_0005>
                                Популярные категории
                            </NaN_0005>
                            <Button>
                                <H6_0012>
                                    Все
                                </H6_0012>
                                <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2dd77510-c3b0-4e7a-a42c-30bf288fcb50" alt="icon"/>
                            </Button>
                        </Title_0006>
                        <Frame16_0001>
                            <Dektop>
                                <ImageArea/>
                                <NaN_0006>
                                    Садовая техника
                                </NaN_0006>
                            </Dektop>
                            <Dektop>
                                <ImageArea_0001/>
                                <NaN_0006>
                                    Стройка
                                </NaN_0006>
                            </Dektop>
                            <Dektop>
                                <ImageArea_0002/>
                                <NaN_0006>
                                    Освещение
                                </NaN_0006>
                            </Dektop>
                            <Dektop>
                                <ImageArea_0003/>
                                <NaN_0006>
                                    Садовая техника
                                </NaN_0006>
                            </Dektop>
                        </Frame16_0001>
                        <Frame17>
                            <Frame22>
                                <ImageArea_0004/>
                                <NaN_0006>
                                    Ванная комната
                                </NaN_0006>
                            </Frame22>
                            <Dektop>
                                <ImageArea_0005/>
                                <NaN_0011>
                                    Спецодежда и средства индивидуальной защиты
                                </NaN_0011>
                            </Dektop>
                            <Dektop>
                                <ImageArea/>
                                <NaN_0006>
                                    Садовая техника
                                </NaN_0006>
                            </Dektop>
                            <Dektop>
                                <ImageArea/>
                                <NaN_0006>
                                    Садовая техника
                                </NaN_0006>
                            </Dektop>
                        </Frame17>
                    </Frame19>
                </Frame29>
                <Frame21>
                    <Frame17_0001>
                        <Frame23>
                            <Image25/>
                        </Frame23>
                        <Frame23>
                            <Image25_0001/>
                        </Frame23>
                        <Frame23>
                            <Image25_0002/>
                        </Frame23>
                        <Frame23>
                            <Image25_0003/>
                        </Frame23>
                        <Frame23>
                            <Image25_0004/>
                        </Frame23>
                        <Frame23>
                            <Image25_0005/>
                        </Frame23>
                    </Frame17_0001>
                </Frame21>
                <Frame20>
                    <Title_0007>
                        <NaN_0005>
                            Хиты продаж
                        </NaN_0005>
                    </Title_0007>
                    <Frame18_0001>
                        <Frame16>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9a967ed4-083e-414a-b0f8-d5c066ae37d9" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/90975ecb-6da7-4c47-adf3-8a4ff760ced7" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1b8cd7f6-b2d0-4a9c-b5f6-f1431e083d3c" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1f06b1c3-f404-475b-80fc-2f446a9bce53" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                            <ProductCardDesktop>
                                <ImageContainer>
                                    <PhotoArea/>
                                </ImageContainer>
                                <TitlePrice>
                                    <Price>
                                        <Forester26X40Forester>
                                            Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                        </Forester26X40Forester>
                                    </Price>
                                    <StarsReviews>
                                        <Stars>
                                            <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b790245c-dfd8-47bb-b760-9b7e50814934" alt="icon"/>
                                            <_45>
                                                4.5
                                            </_45>
                                        </Stars>
                                        <_98>
                                            98 оценок
                                        </_98>
                                    </StarsReviews>
                                    <Title_0001>
                                        <_560>
                                            560₽
                                        </_560>
                                    </Title_0001>
                                </TitlePrice>
                                <Button_0006>
                                    <H6_0007>
                                        В Корзину
                                    </H6_0007>
                                </Button_0006>
                            </ProductCardDesktop>
                        </Frame16>
                        <Button_0019>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f19ca5b4-33ec-49d7-abbb-7ee22b761163" alt="icon"/>
                        </Button_0019>
                        <Button_0020>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9718729a-049e-4cb2-ad1c-79e013f179b6" alt="icon"/>
                        </Button_0020>
                    </Frame18_0001>
                </Frame20>
            </Frame30>
            <Row_0001>
                <Frame197>
                    <ColMd3>
                        <Frame198>
                            <NaN_0015>
                                Строй Дом Маркет
                            </NaN_0015>
                            <Paragraph>
                                Интернет магазин инструментов
                            </Paragraph>
                        </Frame198>
                        <SocialMedia>
                            <Facebook src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/cde5fc0c-627b-44e4-a7de-71bc23343093" alt="icon"/>
                            <Instagram src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e08fea1f-b6ee-4c0d-b418-b0c66997b8ee" alt="icon"/>
                            <Twitter>
                                <AntDesignTwitterOutlined>
                                    <Vector_0002 xmlns="http://www.w3.org/2000/svg">
                                        <path fill="white" d="M6.91075 18C15.213 18 19.7546 11.0731 19.7546 5.07669C19.7546 4.88285 19.7546 4.68625 19.7464 4.49241C20.6306 3.84789 21.3937 3.04993 22 2.13592C21.1741 2.50262 20.2988 2.7443 19.4026 2.85312C20.3466 2.28495 21.0536 1.391 21.3923 0.337403C20.5054 0.86647 19.5346 1.23787 18.5226 1.43534C17.8423 0.705724 16.9419 0.222372 15.9611 0.0601592C14.9803 -0.102054 13.9737 0.0659244 13.0973 0.538075C12.2209 1.01023 11.5236 1.7602 11.1134 2.67182C10.7031 3.58345 10.6029 4.60585 10.8281 5.58066C9.03339 5.49005 7.27762 5.02057 5.67468 4.20269C4.07175 3.3848 2.65744 2.23678 1.5235 0.833069C0.947843 1.83421 0.772164 3.01843 1.03214 4.14526C1.29211 5.27209 1.96825 6.25705 2.92325 6.90013C2.20762 6.87565 1.50772 6.68215 0.88 6.33524L0.88 6.39754C0.881234 7.44631 1.24205 8.46247 1.90145 9.27429C2.56086 10.0861 3.4784 10.6438 4.499 10.853C4.11161 10.9605 3.71144 11.014 3.30963 11.0122C3.02635 11.0131 2.74365 10.9867 2.46537 10.9333C2.75383 11.8361 3.3155 12.6254 4.07171 13.1908C4.82793 13.7561 5.74081 14.0691 6.6825 14.0859C5.08276 15.3511 3.10668 16.0373 1.0725 16.034C0.714066 16.0355 0.355882 16.0147 0 15.9716C2.06458 17.297 4.46228 18.0008 6.91075 18L6.91075 18Z"/>
                                    </Vector_0002>
                                </AntDesignTwitterOutlined>
                            </Twitter>
                        </SocialMedia>
                    </ColMd3>
                    <Frame195>
                        <Frame11>
                            <ScheduleFill0Wght300Grad0Opsz2411 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2ab87fb3-a615-43c4-b3e3-1e47f3acea04" alt="icon"/>
                            <_90020009001700>
                                Пн.-Сб.: 9:00-20:00, Вс.: 9:00-17:00
                            </_90020009001700>
                        </Frame11>
                        <BtnSm20_0001>
                            <CallFill0Wght300Grad0Opsz241 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/86c33509-d69d-4f87-a5d2-e4a6d5296730" alt="icon"/>
                            <H6_0004>
                                +7(909) 623-22-33
                            </H6_0004>
                        </BtnSm20_0001>
                        <Info>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/813a67fa-1403-48ee-ad56-485fe28cdf30" alt="icon"/>
                            <H6_0004>
                                Москва
                            </H6_0004>
                        </Info>
                        <Info>
                            <MailFill0Wght300Grad0Opsz241 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f27f3afa-0070-4578-8c4c-0451c249ac7e" alt="icon"/>
                            <H6_0004>
                                электронная почта
                            </H6_0004>
                        </Info>
                    </Frame195>
                </Frame197>
                <Container_0001>
                    <Row_0002>
                        <ColMd6>
                            <_20062023>
                                © 2006–2023. Все права защищены.
                            </_20062023>
                        </ColMd6>
                    </Row_0002>
                </Container_0001>
            </Row_0001>
            <Frame213>
                <CheckCircleFill0Wght400Grad0Opsz241 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b8b1790d-a72c-4393-b2e7-4b6b202cdb90" alt="icon"/>
                <NaN_0016>
                    Товар добавлен в корзину
                </NaN_0016>
            </Frame213>
        </RootWrapperHomepageCategory>
    )
}

const RootWrapperHomepageCategory = styled.div`
	min-height: 100vh;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const NavbarStyle8NavbarLight = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	background: rgb(35, 166, 240);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	position: absolute;
	left: 0px;
	top: 0px;
	width: 1440px;
`;

const Container = styled.div`
	height: 48px;
	overflow: hidden;
	background: rgb(37, 43, 66);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
	align-self: stretch;
	flex-shrink: 0;
`;

const Row = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: flex-start;
	box-sizing: border-box;
	padding: 0px 24px;
	position: absolute;
	left: 0px;
	top: 0px;
	width: 1438px;
`;

const ColMd4 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 10px;
	width: 463px;
	height: 46px;
	box-sizing: border-box;
`;

const Button = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 4px;
	border-radius: 4px;
	height: 30px;
	box-sizing: border-box;
	padding: 2px 12px;
`;

const Icon = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const H6 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	line-height: 22px;
	text-align: center;
`;

const BtnSm20 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 5px;
	border-radius: 5px;
	box-sizing: border-box;
	padding: 10px;
`;

const IcnSettingsIcnXs = styled.img`
	width: 16px;
	height: 16px;
	object-fit: cover;
`;

const H6_0001 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

const ColMd4_0001 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 10px;
	width: 463px;
	box-sizing: border-box;
	padding: 10px;
`;

const NaN_0001 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

const Left = styled.div`
	display: flex;
	justify-content: flex-end;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 8px;
	width: 463px;
	height: 46px;
	box-sizing: border-box;
	padding: 10px;
`;

const Button_0001 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	border-radius: 4px;
	height: 30px;
	box-sizing: border-box;
	padding: 2px 4px;
`;

const Frame15 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	gap: 16px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 16px 0px;
	flex-shrink: 0;
`;

const _4 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	gap: 24px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 0px 38px;
	flex-shrink: 0;
`;

const Frame13 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 24px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Logo = styled.div`
	width: 220px;
	height: 48px;
	position: relative;
`;

const NaN_0002 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Montserrat, sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 8px;
`;

const InputHeader = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 12px;
	border: solid 1px rgb(230, 230, 230);
	border-radius: 5px;
	width: 944px;
	height: 48px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
`;

const Button_0002 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	background: rgb(235, 235, 235);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 0px 8px;
	flex-shrink: 0;
`;

const H6_0003 = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 13px;
	font-family: Montserrat, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 26px;
`;

const NaN_0003 = styled.span`
	color: rgba(0, 0, 0, 0.6);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: center;
`;

const Frame11 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	box-sizing: border-box;
`;

const Button_0003 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	border-radius: 4px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 2px 12px;
	flex-shrink: 0;
`;

const H6_0004 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	text-align: center;
`;

const Button_0004 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	border-radius: 4px;
	box-sizing: border-box;
	padding: 2px 12px;
`;

const Badge = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	border-radius: 100px;
	background: rgb(255, 0, 0);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 0px 7px;
`;

const Text = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	line-height: 20px;
	text-align: left;
`;

const _2 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 24px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 0px 40px;
	flex-shrink: 0;
`;

const Button_0005 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 4px;
	border-radius: 4px;
	height: 42px;
	background: linear-gradient(-90deg, rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.2));
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 10px 12px;
`;

const H6_0006 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 22px;
	text-align: center;
`;

const Frame14 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 28px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Tab = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	height: 42px;
	box-sizing: border-box;
	padding: 1px 8px;
`;

const Text_0001 = styled.span`
	color: rgba(255, 255, 255, 0.95);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 500;
	line-height: 22px;
	text-align: left;
`;

const Banner = styled.div`
	width: 1342px;
	height: 464px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/8f09/38df/9b8981b3f884c8926a0ef6179f976f9b?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Ht-5jZcxbidqNqIDGvQUz1yYQrKFkIo1IBrvDzGl1qK6hrp1J86PSwkiSy~~7npBjEYW4d1VQFiVCMq-E6TxXXYC6JPpPVYSlRTn0wr8gGlLqS3PBzMRPmm0aELT8GowVpMyh1hD2RjYsLR-hXuNwKPojRwtu~CNqD1Af7suloHdXTR15UiSRCVmzGENvbaEpxcsUhNjJUSSfYP8SveyKWxafZvJLYD2YwB4BTSJ19jcU3WO2KlbdAn1KmNhz8HBXklJZtvd6lYJLwS~SegpkGVRQDSe79ae2xH1WwQuenAJEHSKrsnK4TbW51eKSJ6rDY7gCIofIS73kZMDdeCEvQ__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border-radius: 20px;
	position: absolute;
	box-shadow: 0px 0px 10px 3px rgba(0, 0, 0, 0.11);
	left: calc((calc((50% + 0px)) - 671px));
	top: 219px;
`;

const ButtonNext = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	box-sizing: border-box;
	padding: 10px;
	position: absolute;
	left: 1279px;
	top: 0px;
	width: 62px;
	height: 464px;
`;

const Vector = styled.svg`
	width: 24px;
	height: 44px;
`;

const ButtonPrevious = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	box-sizing: border-box;
	padding: 10px;
	position: absolute;
	left: 62px;
	top: 0px;
	transform: rotate(-180deg);
	transform-origin: top left;
	width: 62px;
	height: 464px;
`;

const Pagination = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	gap: 4px;
	box-sizing: border-box;
	position: absolute;
	left: calc((calc((50% + 0px)) - 26px));
	bottom: 20px;
`;

const Lines = styled.div`
	width: 10px;
	height: 10px;
	box-shadow: 0px 0px 3px  rgba(0, 0, 0, 0.2);
	background: rgb(35, 166, 240);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 20px;
`;

const Lines_0001 = styled.div`
	width: 10px;
	height: 10px;
	box-shadow: 0px 0px 3px  rgba(0, 0, 0, 0.2);
	background: linear-gradient(-90deg, rgba(255, 255, 255, 0.9), rgba(255, 255, 255, 0.9));
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 20px;
`;

const Frame30 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	gap: 90px;
	box-sizing: border-box;
	position: absolute;
	left: 0px;
	top: 766px;
	width: 1440px;
`;

const Frame18 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 16px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 0px 60px;
	flex-shrink: 0;
`;

const Title = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	height: 42px;
	box-sizing: border-box;
	padding: 10px;
	flex-shrink: 0;
`;

const NaN_0004 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 22px;
	text-align: center;
`;

const Frame18_0001 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame16 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: flex-start;
	flex: 1;
	width: 1320px;
	box-sizing: border-box;
`;

const ProductCardDesktop = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 8px;
	border-radius: 6px;
	width: 240px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 20px;
`;

const ImageContainer = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	height: 200px;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const PhotoArea = styled.div`
	width: 188px;
	height: 188px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/66c4/4fd1/243b1f5431c096e58e57aa8ec38dae7a?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=F6mugLHvCeVJ817NJEoCYep7PAFD~f5jk1SGzaAyMLbSoLPIYS80su9z~4FeeOOGC6iTFJVxToougdz8B7-igHUl9DFboToAtiD9Z2onkcOGqtXP3YTEIYKeTjy4TwQZtmuTo444k6FgteO3O34L4y~AoslDYxLeTVik7JsTptXd0YpBF3GXYXq1hMMdnsPyPIej4m1-m~1yGE7csdVugI-irSJs0ijpgus80iUEdQn9kGm4wIuH4TLtBHYLrdfkwy4DNOxbVbfwL3T0SgZwd4KXBI0Rv3gFTIKgBWD08Pf6wdW8UWY1GQipM42jgXeSz16JmPtBiwEXjrF9PvWKOA__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const TitlePrice = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 4px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Price = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Forester26X40Forester = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 200px;
	flex: 1;
`;

const StarsReviews = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 8px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Stars = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 4px;
	box-sizing: border-box;
`;

const Star1 = styled.img`
	width: 18px;
	height: 18px;
	object-fit: cover;
`;

const _45 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const _98 = styled.span`
	color: rgba(0, 0, 0, 0.7);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Title_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const _560 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	text-align: left;
`;

const Button_0006 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	border-radius: 4px;
	height: 42px;
	background: rgb(35, 166, 240);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 10px 12px;
	opacity: 0;
`;

const H6_0007 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	line-height: 22px;
	text-align: center;
`;

const Button_0011 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 0px 4px  rgba(0, 0, 0, 0.3);
	border-radius: 54px;
	width: 42px;
	height: 42px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	transform: rotate(-180deg);
	transform-origin: top left;
`;

const Button_0012 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 0px 4px  rgba(0, 0, 0, 0.3);
	border-radius: 54px;
	width: 42px;
	height: 42px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
`;

const Frame29 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 10px;
	width: 1444px;
	background: rgb(245, 245, 245);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 60px 0px;
`;

const Frame19 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	gap: 10px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 0px 60px;
	flex-shrink: 0;
`;

const Title_0006 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	height: 42px;
	box-sizing: border-box;
	padding: 10px;
	flex-shrink: 0;
`;

const NaN_0005 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	text-align: center;
`;

const H6_0012 = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	line-height: 22px;
	text-align: center;
`;

const Frame16_0001 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: flex-start;
	align-self: stretch;
	height: 233px;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Dektop = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 12px;
	border-radius: 8px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 12px;
`;

const ImageArea = styled.div`
	width: 300px;
	height: 175px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/fd5f/ae45/41b7045c5e1652ffaa15338d299a2a12?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=PjYShKn0LrjixBQqBbKFRifyBprJuXBxWGonbHoM30NH4VKhRzJOuL989w2-xSXMlRzqC6cGaOcnRjFZBIcOQvRdqvIvBxMsMoXzr6beYHYavhklnhMv9qDuZIcF~d6aJ8Dp6I11TXgNiS5aAvk0KnzuZBtjQI7N6X0YjAlt8ylDh4pvq51e1PFg4poTJdw~2Hg372ZW~xT2CMgJ~~1ClFCZWJkfmKGCp~zXjJnL--8ImFl~F6McXpJLZOfAg6HnaizKaB93geGSoL-dqQXGrI-lPsxc0e35NHS3FmgQgJW2NMMS~wsn-imsxM6S2Lexlrf78Yqt6zpz3gtYQFL9EA__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const NaN_0006 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 600;
	line-height: 22px;
	text-align: center;
`;

const ImageArea_0001 = styled.div`
	width: 300px;
	height: 175px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/e28d/c9b4/dc0ff451712bbfd6cb6fd46e2ee1e686?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=MDvZEYzrEsEkUqNymRRqWbev8zdeJt6H670lM8pYQAggSSsdw3COrQRV6C8Ms4TqfbjmKnyDknsLMjk~W2vqbuuVssJjJxgi8kxFfLErOBR4joF-~R6V3Y5FgAVj-YeasiS71FDGEZtVUlo6S2L1hHJLClSXO91UHabASBBKHZN4sPj0bFV9mcaxd2y00Fz~2eBiRdCNUbvjEEFshgW5ihaQPUis414BgTG12wvIP1rECosFxszOrGCQvjK825iZDLa~4VoaxS2tdHyU4q1sVOusOW38QTCOUoVmq8Z2lukYjhn28GmEihnmzryBEqv2QB3g~lgjoZjhvkjgEvnbag__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const ImageArea_0002 = styled.div`
	width: 300px;
	height: 175px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/6376/cf78/1b4cc740003952e9e682bbe775eacd48?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=YZ6zuicTh4FndfHSP9TLUCA9wx524YGTSe2iuTXUu-1VFg7JtVtBjrFZTnl81VR1Wx~IH1Zxrtyy411AWwIAtYTTYOxdoQoGrMIwLo0Ysz5Nrh3XEatp4WkO6TNJuKlxAJUr3pqiyULZ2YXqRXQCUdXmrUJsNzyroi490G-JyNHMXJrbin5hO5BHwwFcVzuEm~HjkF2M8Pq-knkyvd50xcwf1M8B6J2xKhz4d-eLqIIHA6EtDjLHLfDpCudri1~~RNXciaWAXxVk-I4JkvAdX1ggxQl656H7UH9cZQngc7CCKFITi8uW6kVHznFA2oDVVTUJ11wxXiFk24RuBKNgpg__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const ImageArea_0003 = styled.div`
	width: 300px;
	height: 175px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/6376/cf78/1b4cc740003952e9e682bbe775eacd48?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=YZ6zuicTh4FndfHSP9TLUCA9wx524YGTSe2iuTXUu-1VFg7JtVtBjrFZTnl81VR1Wx~IH1Zxrtyy411AWwIAtYTTYOxdoQoGrMIwLo0Ysz5Nrh3XEatp4WkO6TNJuKlxAJUr3pqiyULZ2YXqRXQCUdXmrUJsNzyroi490G-JyNHMXJrbin5hO5BHwwFcVzuEm~HjkF2M8Pq-knkyvd50xcwf1M8B6J2xKhz4d-eLqIIHA6EtDjLHLfDpCudri1~~RNXciaWAXxVk-I4JkvAdX1ggxQl656H7UH9cZQngc7CCKFITi8uW6kVHznFA2oDVVTUJ11wxXiFk24RuBKNgpg__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	position: relative;
`;

const Frame17 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame22 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 12px;
	border-radius: 8px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 12px;
`;

const ImageArea_0004 = styled.div`
	width: 300px;
	height: 175px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/f7b2/b438/ce52fb9d42aa29307af7b0f8cbfc4608?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=kG6Aa-D1i2SfTJil9SoFuFKFcnRCZJVS866woAIYJ-WAwdnWWGqnEpQwYLP2~AZhGyS1z59EpbRYgtaUGyfTrc5dqSlyj3TN~qckthimyGElq4YP6lsCGV9~EcoaiuMsfQsEtir~B9ywu9RiL0B-2toVp5gPJIk6fVBzMbA4sVqBCwmNntkEbPpznRM~E8ZaWucY-LsXTgGOxOoy~MSIQKs1Rw3WZzc7pK5NeI2-tvO~YhZ~qrabCg3wLCLW40hVCewjVgOL3cObWNWIHGuUD0cPMUhuw~nipUXgzEmA9zwLyJDegzqg8ZlfLGFEDEsw4PKHhu8EgsRxtsjs~mg7dA__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const ImageArea_0005 = styled.div`
	width: 300px;
	height: 175px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/666d/52f8/623ba3df96c3970e3a4cdc9a815a6a27?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=R2P-HBOftKaR768u9qgxe3Ken3QewDoyGh0yBSgLv6XqDOrsOM08ThGLYLWWr62bobrtuyDb86IygyQQG5RBSe9rYq2USQUKEMBjAVpzZmPoXuKJQjawxN68SZiAYzrsLVMN8MDTMef3a46NV63KWdrc3cHDJMYKLV-h6cgSK6IZLMgwj~d3Q3KFF3UG0e8qbFDeFve4DP6qNndP8Pffmi8~ntUXCfFrYPF4Q9nDmwTbi55YaMgDFNKKNfNBzvDKDrd6yOHWh5ctDLQFUpUeCk1tLV4~jb7mMHgtZ6-bx3bMZrUqS1TkatbGqXLR10RTqlr17VTUeV8~J6aiqFC~lw__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const NaN_0011 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 600;
	line-height: 22px;
	text-align: center;
	align-self: stretch;
	flex-shrink: 0;
`;

const Frame21 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 16px;
	box-sizing: border-box;
`;

const Frame17_0001 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: center;
	flex: none;
	width: 1340px;
	box-sizing: border-box;
`;

const Frame23 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 10px 28px;
`;

const Image25 = styled.div`
	width: 136px;
	height: 48px;
	background: url(https://s3-alpha-sig.figma.com/img/60c0/56e5/b7bbbe9e7d4d41853496f2b309417a9c?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=LD4XGeaK02Am0-wMurW3HFad0~DS8VcRp7Yh4CqBuUzd5MqEm1lZT6sUJhyzs7wggfa3HRfqWtecV4CHXTzyJahlX-4XtDXJ~nVbS0vHF1Dr35V3gj~fLzB9h7lAdIky8eUWHC6Eo2svwLR--PSPgPWDUM5CBxk6WW2fe0LysrFXFMkfbYYgBnzsMwDrKBWhUTx3IdDYAmlCS77do0Gx86NM-BAwxXhzoWHj0o8meeRc5mQ3tBpaBBMhRNOaMDmcN5w~FXfKmmtuvkOPDncHpz04ZjZ6YWprviJvoJzHr37t-ha5w3bN4AWB~lZACaugpjY6I-RmGEkZTPojlooEEA__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
`;

const Image25_0001 = styled.div`
	width: 136px;
	height: 48px;
	background: url(https://s3-alpha-sig.figma.com/img/a002/64a2/95a3660a5574b61f66e71fde9a04cc9b?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=K3Y6GiZGqEI-ooZ5X151Xx-QDFBnt~eIGcj~LhKRZ4ugikZQwNzYuWRknZInfmYQL-2MbFRVN9tQLZX9e468QGpLJaT6H9P8O2eSccefZj0z3RJPHBQN9fmvdIt61P1UmBc4szoScHR0c4ChZAt~3TkcJMpi1MT0x1hPCp3On3Cu8E-mccge1Y3i1gFuRP0XaybgC5TaduDH1SRQeanpZm-Pye5rDSSwntrutC9Dkwp6tHdAj66MiveTGgvJPCbHoSD5bdWDVX6gqosqJa0R5u3Z7TVjcStXanDxbb336DvkYs~HTSTiv-abACLOsW8O4dwBMYotCzJKgAJ5rOqieQ__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
`;

const Image25_0002 = styled.div`
	width: 136px;
	height: 48px;
	background: url(https://s3-alpha-sig.figma.com/img/1b44/2da7/246417fdfe776c791c2cbd5779048323?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=IaCWOwhwAujnUo32xVbVM2f4eFH~5qF71NiL6oSadKQqatuFHDZJY-H4PJeFMC8pfzqte1iL4R5Kw0gQtD8u445icl1OOyvj-G-5cvOchp-usO9xjhrvTq0eQeMzciR6hE3UP6Ys70TG7J5bATb-~MCGltoxJmZeDSpypVC1ly~yPYjRZre6oQV9WwhhRQw7NthqpfTRHCn3~qGoLds5TvOYx6VlzvOX-C9H~45CkNJBsBTDb9Y9wW7WDQ6znLsSEuBLbYPpr76~1~iihu0HCsh523gnkuyHQZosutHU64LbEzhO1leFExolgrelAiFGhX01AuC~smj26g8HNbl~HA__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
`;

const Image25_0003 = styled.div`
	width: 136px;
	height: 48px;
	background: url(https://s3-alpha-sig.figma.com/img/f64d/4815/54352c31d85e7dacefd7b77b5a2e3f06?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Jr6h5y5ShY3d5OY3VPiNKOzycTVULk4y9NQjdsFJYABXovzxU5B~bdngp6sC~nssZkfOZotKJwLr7LsDIKJfpkzaHzXflBNd6JF2uhGt91aCU1V8kAubqixs-sHGOihhugu2al5X1EkP9UK6t9ai358DMa~MuZQYY7I8FFWXbvH80B5WmgTRqz3xvNb1az477BUVrHPchaNM0DyNRuRI8ohBT8QVooojiiPljT9tZV4NsDI8WWafTRXY0QL1~cc6u0mqb8dpvRI92NzI~bSss9Ud9Te6s3MlBHbFKn7Qo9N2HljbJagyea5G9xFg9qwUz7L4wKG1Kvnn953IW1sWKQ__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
`;

const Image25_0004 = styled.div`
	width: 136px;
	height: 48px;
	background: url(https://s3-alpha-sig.figma.com/img/6a80/6c15/583bd28a2c86c5c1aa1afec9b4db9285?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Rl~poyLtRH5a1Um8Q1bTc3gp9zMm2UaoylMblbRkCY5RnHB8Uo2qDK-ksOPD0OiYeCl5Y8hrx61aVBZRcsHr0XcQ9jw~wzLH9gV8bD6IPuDdW-ufqQyjupyiwB397t8PUFFVzN6p8Hf6ebIZZUXIyQmEVaBnKv0GSrxD123JVFqHlbkrBe6SWgPQS5ZghNnOTig9NykhOVoY4vjdCwQAewDuUkP4g0bYn83d5ek3UQakFLkg4llrlgKPG~zkxpWSNUFmduOfluYuYBektSHNIB8~PLM9R80XvJMnCl5innY4WB~3J-M8ZGaNJoUARfTMcm0qqciiwRFD1TIJB7NKGA__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
`;

const Image25_0005 = styled.div`
	width: 136px;
	height: 48px;
	background: url(https://s3-alpha-sig.figma.com/img/91e1/50b6/384c8088190c21d4088181d9011bf7d7?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=fEKfKAWWaTXPeeJlFUa9YPi~ZcWJVb~40H4wvpVwhrmNkTi1pRaKccPNbNswhoDyCoH3qiN21v-Yh1P3nz1ZVWdAOt-wVXfNLf7f7YyiTSILcNQEt7RBVDOSEcw74g52Ej9UmcgU9jP5fuBHqI4SvI1OdG3ivlSYN01zav6gEi0F1AyyCEveCTKTUfVcN9G1QoahSny48tQw-2GCEuDh51rH4CNocviOBCFmM7XhvzpV2pfHT0dhYxYp6QDzwMpUgtp5qDDiSI2GUorYwLLM4DAjONiLar5lo-fLwDWPvCvc8MYuEk4XvYOERZ-ymETu7c8R9BodjrI2eKD0kYU~UQ__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
`;

const Frame20 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	gap: 16px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 0px 60px;
	flex-shrink: 0;
`;

const Title_0007 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	height: 42px;
	box-sizing: border-box;
	padding: 7px 10px;
	flex-shrink: 0;
`;

const Button_0019 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	box-shadow: 0px 1px 2px  rgba(0, 0, 0, 0.3),0px 1px 3px 1px rgba(0, 0, 0, 0.15);
	border-radius: 54px;
	width: 42px;
	height: 42px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 10px 20px;
	transform: rotate(-180deg);
	transform-origin: top left;
`;

const Button_0020 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 1px 2px  rgba(0, 0, 0, 0.3),0px 1px 3px 1px rgba(0, 0, 0, 0.15);
	border-radius: 54px;
	width: 42px;
	height: 42px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
`;

const Row_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	gap: 24px;
	background: rgb(42, 124, 199);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 30px 60px 0px;
	position: absolute;
	left: 0px;
	bottom: 0px;
	width: 1440px;
`;

const Frame197 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 8px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const ColMd3 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame198 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 8px;
	box-sizing: border-box;
`;

const NaN_0015 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Montserrat, sans-serif;
	font-weight: 800;
	text-align: left;
`;

const Paragraph = styled.span`
	color: rgba(255, 255, 255, 0.7);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

const SocialMedia = styled.div`
	display: flex;
	justify-content: flex-end;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 20px;
	width: 1057px;
	box-sizing: border-box;
`;

const Facebook = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Instagram = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Twitter = styled.div`
	width: 24px;
	height: 20px;
	overflow: hidden;
	position: relative;
`;

const AntDesignTwitterOutlined = styled.div`
	width: 24px;
	height: 20px;
	overflow: hidden;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Vector_0002 = styled.svg`
	width: 22px;
	height: 18px;
	position: absolute;
	left: 2px;
	top: 1px;
	right: 1px;
	bottom: 1px;
`;

const Frame195 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 50px;
	box-sizing: border-box;
`;

const ScheduleFill0Wght300Grad0Opsz2411 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const _90020009001700 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	text-align: center;
`;

const BtnSm20_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	border-radius: 5px;
	box-sizing: border-box;
`;

const CallFill0Wght300Grad0Opsz241 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Info = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	border-radius: 4px;
	box-sizing: border-box;
	padding: 2px 0px;
`;

const MailFill0Wght300Grad0Opsz241 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Container_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	width: 1050px;
	box-sizing: border-box;
	padding: 25px 0px;
`;

const Row_0002 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 213px;
	box-sizing: border-box;
`;

const ColMd6 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	width: 513px;
	box-sizing: border-box;
`;

const _20062023 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

const Frame213 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 8px;
	box-shadow: 0px 0px 5px 2px rgba(0, 0, 0, 0.2);
	border-radius: 8px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 8px;
	position: absolute;
	left: 1226px;
	top: 196px;
`;

const CheckCircleFill0Wght400Grad0Opsz241 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const NaN_0016 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	text-align: left;
`;

