import React from "react";
import styled from "@emotion/styled";
/**
 * `<ProductPage>` ('Product page')
 * - [Open in Figma](https://figma.com/file/1FTzSY1Y0v5oLlpOkNYsQj?node-id=82:20433)
 * - [Open in Grida](https://code.grida.co/files/1FTzSY1Y0v5oLlpOkNYsQj?node=82:20433)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <ProductPage/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a5d14d26-12d4-47b8-aea8-39f0ed224f27)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://1FTzSY1Y0v5oLlpOkNYsQj/82:20433 -->
 */
export function ProductPage() {
    return (
        <RootWrapperProductPage>
            <NavbarStyle8NavbarLight>
                <Container>
                    <Row>
                        <ColMd4>
                            <Button>
                                <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2f695947-963c-41c0-b9fd-178307927c17" alt="icon"/>
                                <H6>
                                    Москва
                                </H6>
                            </Button>
                            <BtnSm20>
                                <IcnSettingsIcnXs src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/40b01921-3963-478b-a489-4f99af314a5b" alt="icon"/>
                                <H6_0001>
                                    +7(909) 623-22-33
                                </H6_0001>
                            </BtnSm20>
                        </ColMd4>
                        <ColMd4_0001>
                            <NaN_0001>
                                Интернет магазин инструментов
                            </NaN_0001>
                        </ColMd4_0001>
                        <Left>
                            <Button_0001>
                                <H6>
                                    Контакты
                                </H6>
                            </Button_0001>
                        </Left>
                    </Row>
                </Container>
                <Frame15>
                    <_4>
                        <Frame13>
                            <Logo>
                                <NaN_0002>
                                    Строй Дом Маркет
                                </NaN_0002>
                            </Logo>
                            <InputHeader>
                                <Button_0002>
                                    <H6_0003>
                                        Все
                                    </H6_0003>
                                    <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/cf746cc9-017f-4d18-8e19-2e137e37a024" alt="icon"/>
                                </Button_0002>
                                <NaN_0003>
                                    Поиск
                                </NaN_0003>
                            </InputHeader>
                            <Frame11>
                                <Button_0003>
                                    <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f4e8ba66-19d4-450a-a721-53c7c501cd51" alt="icon"/>
                                    <H6_0004>
                                        Войти
                                    </H6_0004>
                                </Button_0003>
                                <Button_0004>
                                    <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0e1ca8ea-d504-4bb7-9ece-d67186f0e1db" alt="icon"/>
                                    <H6_0004>
                                        Корзина
                                    </H6_0004>
                                    <Badge>
                                        <Text>
                                            1
                                        </Text>
                                    </Badge>
                                </Button_0004>
                            </Frame11>
                        </Frame13>
                    </_4>
                    <_2>
                        <Button_0005>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/eeb2c69f-b0bf-424c-9f9a-4fb036d1f48e" alt="icon"/>
                            <H6_0006>
                                Каталог товаров
                            </H6_0006>
                        </Button_0005>
                        <Frame14>
                            <Tab>
                                <Text_0001>
                                    Стройкa
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Сад и досуг
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Техника
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Все для дома
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Кухня
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Ванная комната
                                </Text_0001>
                            </Tab>
                            <Tab>
                                <Text_0001>
                                    Строительное оборудование
                                </Text_0001>
                            </Tab>
                        </Frame14>
                    </_2>
                </Frame15>
            </NavbarStyle8NavbarLight>
            <Row_0001>
                <Frame197>
                    <ColMd3>
                        <Frame198>
                            <NaN_0004>
                                Строй Дом Маркет
                            </NaN_0004>
                            <Paragraph>
                                Интернет магазин инструментов
                            </Paragraph>
                        </Frame198>
                        <SocialMedia>
                            <Facebook src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/609ed492-f2b9-4804-9bd4-fa0bf0087072" alt="icon"/>
                            <Instagram src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b70064ea-0a53-4067-9c5c-d04aaf8ce217" alt="icon"/>
                            <Twitter>
                                <AntDesignTwitterOutlined>
                                    <Vector xmlns="http://www.w3.org/2000/svg">
                                        <path fill="white" d="M6.91075 18C15.213 18 19.7546 11.0731 19.7546 5.07669C19.7546 4.88285 19.7546 4.68625 19.7464 4.49241C20.6306 3.84789 21.3937 3.04993 22 2.13592C21.1741 2.50262 20.2988 2.7443 19.4026 2.85312C20.3466 2.28495 21.0536 1.391 21.3923 0.337403C20.5054 0.86647 19.5346 1.23787 18.5226 1.43534C17.8423 0.705724 16.9419 0.222372 15.9611 0.0601592C14.9803 -0.102054 13.9737 0.0659244 13.0973 0.538075C12.2209 1.01023 11.5236 1.7602 11.1134 2.67182C10.7031 3.58345 10.6029 4.60585 10.8281 5.58066C9.03339 5.49005 7.27762 5.02057 5.67468 4.20269C4.07175 3.3848 2.65744 2.23678 1.5235 0.833069C0.947843 1.83421 0.772164 3.01843 1.03214 4.14526C1.29211 5.27209 1.96825 6.25705 2.92325 6.90013C2.20762 6.87565 1.50772 6.68215 0.88 6.33524L0.88 6.39754C0.881234 7.44631 1.24205 8.46247 1.90145 9.27429C2.56086 10.0861 3.4784 10.6438 4.499 10.853C4.11161 10.9605 3.71144 11.014 3.30963 11.0122C3.02635 11.0131 2.74365 10.9867 2.46537 10.9333C2.75383 11.8361 3.3155 12.6254 4.07171 13.1908C4.82793 13.7561 5.74081 14.0691 6.6825 14.0859C5.08276 15.3511 3.10668 16.0373 1.0725 16.034C0.714066 16.0355 0.355882 16.0147 0 15.9716C2.06458 17.297 4.46228 18.0008 6.91075 18L6.91075 18Z"/>
                                    </Vector>
                                </AntDesignTwitterOutlined>
                            </Twitter>
                        </SocialMedia>
                    </ColMd3>
                    <Frame195>
                        <Frame11>
                            <ScheduleFill0Wght300Grad0Opsz2411 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/36782362-219c-48aa-b34b-f88d4e0c16b5" alt="icon"/>
                            <_90020009001700>
                                Пн.-Сб.: 9:00-20:00, Вс.: 9:00-17:00
                            </_90020009001700>
                        </Frame11>
                        <BtnSm20_0001>
                            <CallFill0Wght300Grad0Opsz241 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9451e4d7-f46c-485b-89ca-d724e2fd9cd5" alt="icon"/>
                            <H6_0004>
                                +7(909) 623-22-33
                            </H6_0004>
                        </BtnSm20_0001>
                        <Info>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/48ded5bb-1f60-4676-8eca-db71c2d0c2a6" alt="icon"/>
                            <H6_0004>
                                Москва
                            </H6_0004>
                        </Info>
                        <Info>
                            <MailFill0Wght300Grad0Opsz241 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b9b07df5-1149-4029-bc6f-863b76615686" alt="icon"/>
                            <H6_0004>
                                электронная почта
                            </H6_0004>
                        </Info>
                    </Frame195>
                </Frame197>
                <Container_0001>
                    <Row_0002>
                        <ColMd6>
                            <_20062023>
                                © 2006–2023. Все права защищены.
                            </_20062023>
                        </ColMd6>
                    </Row_0002>
                </Container_0001>
            </Row_0001>
            <Breadcrumb>
                <_1StItem>
                    <_1StItemLabel>
                        Главная
                    </_1StItemLabel>
                </_1StItem>
                <ComponentsSeparator>
                    <Separator>
                        /
                    </Separator>
                </ComponentsSeparator>
                <_2NdItem>
                    <_2NdItem_0001>
                        <_2NdItemLabel>
                            Сад и досуг
                        </_2NdItemLabel>
                    </_2NdItem_0001>
                </_2NdItem>
                <ComponentsSeparator>
                    <Separator>
                        /
                    </Separator>
                </ComponentsSeparator>
                <_2NdToLastItem>
                    <_2NdToLastItem_0001>
                        <_2NdToLastItemLabel>
                            Товары для полива
                        </_2NdToLastItemLabel>
                    </_2NdToLastItem_0001>
                </_2NdToLastItem>
                <ComponentsSeparator>
                    <Separator>
                        /
                    </Separator>
                </ComponentsSeparator>
                <LastItem>
                    <LastItem_0001>
                        <LastItemLabel>
                            Садовые шланги и аксессуары
                        </LastItemLabel>
                    </LastItem_0001>
                </LastItem>
                <ComponentsSeparator>
                    <Separator>
                        /
                    </Separator>
                </ComponentsSeparator>
                <LastItem>
                    <LastItem_0001>
                        <LastItemLabel_0001>
                            Шланг садовый
                        </LastItemLabel_0001>
                    </LastItem_0001>
                </LastItem>
            </Breadcrumb>
            <TitleImage>
                <DaewooDwh51373450>
                    Шланг садовый DAEWOO DWH 5137 3/4" 50 м
                </DaewooDwh51373450>
                <Frame101>
                    <Stars>
                        <Rating src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6f60c2da-866c-47e0-a14d-45db4aa9c6d7" alt="icon"/>
                        <_45>
                            4.5
                        </_45>
                    </Stars>
                    <_45>
                        98 оценок
                    </_45>
                    <Rectangle3/>
                    <Articul>
                        <NaN_0005>
                            Артикул:
                        </NaN_0005>
                        <_45>
                            5062891
                        </_45>
                    </Articul>
                </Frame101>
                <ImagePreview>
                    <Image26/>
                </ImagePreview>
            </TitleImage>
            <Images>
                <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9c672ce9-284b-4b2c-97fd-69ca791a56dd" alt="icon"/>
                <Images_0001>
                    <Image/>
                    <Image_0001/>
                    <Image_0002/>
                    <Image_0003/>
                    <Image_0002/>
                </Images_0001>
                <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c201fc08-5418-4143-8e16-3e705612cecd" alt="icon"/>
            </Images>
            <RightInfo>
                <PriceAddToBag>
                    <Frame105>
                        <_12990>
                            12 990 ₽
                        </_12990>
                        <NaN_0006>
                            Доступен сейчас
                        </NaN_0006>
                    </Frame105>
                    <ShippingSettings>
                        <NaN_0007>
                            Способы  доставки
                        </NaN_0007>
                        <Cards>
                            <Card>
                                <Frame src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6b210726-629f-46c3-8edf-4ad3daae0843" alt="icon"/>
                                <Frame151>
                                    <NaN_0008>
                                        Самовывоз из пункта выдачи
                                    </NaN_0008>
                                    <_34>
                                        3-4 дней
                                    </_34>
                                </Frame151>
                                <Button_0006>
                                    <Icon_0008 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/04126261-7661-4e1f-a4a2-10bfd28b3a07" alt="icon"/>
                                </Button_0006>
                            </Card>
                            <Card>
                                <Frame src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/80e20f18-657b-4020-9232-b310f151e996" alt="icon"/>
                                <Frame151>
                                    <NaN_0009>
                                        На мой адрес
                                    </NaN_0009>
                                    <NaN_0010>
                                        Добавить адресс
                                    </NaN_0010>
                                </Frame151>
                                <Add src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1fe00553-2eee-41dd-899b-333f70c2b850" alt="icon"/>
                            </Card>
                        </Cards>
                    </ShippingSettings>
                    <Frame103>
                        <Button_0007>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/91db2405-854a-471f-a1fe-28577e8cc302" alt="icon"/>
                        </Button_0007>
                        <Frame102>
                            <_1>
                                1
                            </_1>
                        </Frame102>
                        <Button_0008>
                            <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f77a18bc-59b1-413a-aa57-8e8ed841289c" alt="icon"/>
                        </Button_0008>
                    </Frame103>
                    <Button_0009>
                        <H6_0010>
                            В Корзину
                        </H6_0010>
                    </Button_0009>
                </PriceAddToBag>
                <Frame198>
                    <KeyValue>
                        <NaN_0011>
                            <NaN_0012>
                                Информация
                            </NaN_0012>
                        </NaN_0011>
                        <NaN_0007>
                            Светло-коричневый оттенок идеально впишется в любое помещение, древесная фактура станет дополнительным элементом стилей лофт, кантри, модерн.
                        </NaN_0007>
                        <Infos>
                            <InfoItems>
                                <NaN_0014>
                                    Максимальное давление:
                                </NaN_0014>
                                <Lier src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/831e01ff-3068-4c23-8844-7f37f3522167" alt="image of Lier"/>
                                <_30>
                                    30 бар
                                </_30>
                            </InfoItems>
                            <InfoItems_0001>
                                <NaN_0014>
                                    Материал:
                                </NaN_0014>
                                <Lier_0001 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e8344d07-e59d-4e2e-b070-38ab22b914f7" alt="image of Lier"/>
                                <NaN_0016>
                                    ПВХ
                                </NaN_0016>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0014>
                                    Допустимый диапазон температур:
                                </NaN_0014>
                                <Lier_0002 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/28eb212b-f611-4bdb-ba88-d449286b31d3" alt="image of Lier"/>
                                <_30>
                                    от -10 до +60 °С
                                </_30>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0014>
                                    Минимальная температура эксплуатации:
                                </NaN_0014>
                                <Lier_0003 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/5f452ef7-6a6e-4c3e-8264-72af01382851" alt="image of Lier"/>
                                <_30>
                                    -10 °С
                                </_30>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0014>
                                    Минимальная температура эксплуатации:
                                </NaN_0014>
                                <Lier_0003 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b71fd307-b4de-4b5a-995b-a6f2b5346585" alt="image of Lier"/>
                                <_30>
                                    -10 °С
                                </_30>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0014>
                                    Длина
                                </NaN_0014>
                                <Vector1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e6f1c439-a272-4cc7-9308-cab6a2fde579" alt="image of Vector1"/>
                                <Lier_0005 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/44214b22-5b64-41f2-9db3-5d59276eead2" alt="image of Lier"/>
                                <_50>
                                    50м
                                </_50>
                            </InfoItems_0001>
                        </Infos>
                    </KeyValue>
                    <Button_0010>
                        <H6_0011>
                            Все характеристики
                        </H6_0011>
                    </Button_0010>
                </Frame198>
            </RightInfo>
            <Frame108>
                <NaN_0021>
                    О товаре
                </NaN_0021>
                <AboutSection>
                    <AboutSection_0001>
                        <KronostarGalaxy>
                            Пришла пора менять полы? Обратите внимание на ламинат KRONOSTAR Galaxy Дуб Цефей. Покрытие используется для помещений с интенсивной эксплуатацией пола, применяется для отделки квартир, офисов, гостиниц и других общественных и жилых зданий.<br/>
                            Поверхность имитирует структуру дуба с характерными прожилками, сучками и трещинами. Светло-коричневый оттенок идеально впишется в любое помещение, древесная фактура станет дополнительным элементом стилей лофт, кантри, модерн.<br/>

                        </KronostarGalaxy>
                    </AboutSection_0001>
                </AboutSection>
                <Frame107>
                    <KeyValue>
                        <NaN_0011>
                            <NaN_0012>
                                Технические особенности
                            </NaN_0012>
                        </NaN_0011>
                        <Infos>
                            <InfoItems>
                                <NaN_0024>
                                    Максимальное давление:
                                </NaN_0024>
                                <Lier_0006 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/57e410b1-709a-4d84-9583-7e1ae6f20621" alt="image of Lier"/>
                                <_30_0001>
                                    30 бар
                                </_30_0001>
                            </InfoItems>
                            <InfoItems_0001>
                                <NaN_0014>
                                    Материал:
                                </NaN_0014>
                                <Lier_0007 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/56c8a5b3-1d48-4341-94c5-754083d61bb2" alt="image of Lier"/>
                                <NaN_0016>
                                    ПВХ
                                </NaN_0016>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0024>
                                    Допустимый диапазон температур:
                                </NaN_0024>
                                <Lier_0008 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a7d8e56a-0907-48d0-b2e7-c9297b5cdccf" alt="image of Lier"/>
                                <_1060_0001>
                                    от -10 до +60 °С
                                </_1060_0001>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0024>
                                    Минимальная температура эксплуатации:
                                </NaN_0024>
                                <Lier_0009 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3a4f3ed8-2566-4ce8-b0cd-cebf32cd805c" alt="image of Lier"/>
                                <_30>
                                    -10 °С
                                </_30>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0024>
                                    Длина
                                </NaN_0024>
                                <Vector1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c3380c19-1f7a-4584-aede-4546de2b0a72" alt="image of Vector1"/>
                                <Lier_0005 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/18f315a6-f85d-42a4-a360-f83bce23c515" alt="image of Lier"/>
                                <_50>
                                    50м
                                </_50>
                            </InfoItems_0001>
                        </Infos>
                    </KeyValue>
                    <KeyValue>
                        <NaN_0011>
                            <NaN_0012>
                                Общие характеристики
                            </NaN_0012>
                        </NaN_0011>
                        <Infos>
                            <InfoItems>
                                <NaN_0024>
                                    Максимальное давление:
                                </NaN_0024>
                                <Lier_0006 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4152eedb-9435-41a8-aa36-29405da998d3" alt="image of Lier"/>
                                <_30_0001>
                                    30 бар
                                </_30_0001>
                            </InfoItems>
                            <InfoItems_0001>
                                <NaN_0014>
                                    Материал:
                                </NaN_0014>
                                <Lier_0007 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a902c40f-e568-4313-af52-d962bcf7f0ca" alt="image of Lier"/>
                                <NaN_0016>
                                    ПВХ
                                </NaN_0016>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0024>
                                    Минимальная температура эксплуатации:
                                </NaN_0024>
                                <Lier_0009 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/472f3573-4c76-4099-ae08-a4f632f5b17a" alt="image of Lier"/>
                                <_30>
                                    -10 °С
                                </_30>
                            </InfoItems_0001>
                            <InfoItems_0014>
                                <NaN_0024>
                                    Максимальное давление:
                                </NaN_0024>
                                <Lier_0006 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/017822c6-8e34-4db4-876c-a1d359aaed7d" alt="image of Lier"/>
                                <_30_0001>
                                    30 бар
                                </_30_0001>
                            </InfoItems_0014>
                            <InfoItems_0001>
                                <NaN_0024>
                                    Допустимый диапазон температур:
                                </NaN_0024>
                                <Lier_0008 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1ce04909-58cb-46c5-9fb0-e03c171a2601" alt="image of Lier"/>
                                <_1060_0001>
                                    от -10 до +60 °С
                                </_1060_0001>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0024>
                                    Минимальная температура эксплуатации:
                                </NaN_0024>
                                <Lier_0009 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/2e4ea02e-69cc-44d6-9479-90f97608cf8c" alt="image of Lier"/>
                                <_30>
                                    -10 °С
                                </_30>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0024>
                                    Длина
                                </NaN_0024>
                                <Vector1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/48c44509-a467-48d5-b7ef-045145bbb165" alt="image of Vector1"/>
                                <Lier_0005 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d81f8c76-97ec-4e7c-a305-68cb60fb9b2a" alt="image of Lier"/>
                                <_50>
                                    50м
                                </_50>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0014>
                                    Материал:
                                </NaN_0014>
                                <Lier_0007 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f4ba4093-3124-4bf4-8f43-24bcb981b601" alt="image of Lier"/>
                                <NaN_0016>
                                    ПВХ
                                </NaN_0016>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0024>
                                    Длина
                                </NaN_0024>
                                <Vector1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ec65f454-cd71-4caa-bfb9-b0bdd4f80b97" alt="image of Vector1"/>
                                <Lier_0005 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8bc13afb-47e8-42c4-a1fc-84ce772cb149" alt="image of Lier"/>
                                <_50>
                                    50м
                                </_50>
                            </InfoItems_0001>
                            <InfoItems_0001>
                                <NaN_0024>
                                    Минимальная температура эксплуатации:
                                </NaN_0024>
                                <Lier_0009 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9d6d95dc-25ad-42c3-bef5-c53f805eb2e7" alt="image of Lier"/>
                                <_30>
                                    -10 °С
                                </_30>
                            </InfoItems_0001>
                        </Infos>
                    </KeyValue>
                </Frame107>
            </Frame108>
            <Frame116>
                <Accordion>
                    <AccordionSummary>
                        <Container_0002>
                            <Typography>
                                <NaN_0044>
                                    Подробнее
                                </NaN_0044>
                            </Typography>
                            <AccordionExpandIcon>
                                <IconButton src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8e4eccf1-68fc-408c-8452-6a326fd0deaa" alt="icon"/>
                            </AccordionExpandIcon>
                        </Container_0002>
                    </AccordionSummary>
                    <DividerContainer>
                        <DividerHorizontal>
                            <MinHeight/>
                            <Divider/>
                        </DividerHorizontal>
                    </DividerContainer>
                </Accordion>
                <Accordion>
                    <AccordionSummary>
                        <Container_0002>
                            <Typography_0001>
                                <Frame114>
                                    <NaN_0044>
                                        Отзывы
                                    </NaN_0044>
                                    <_45>
                                        20
                                    </_45>
                                </Frame114>
                            </Typography_0001>
                            <Frame113>
                                <Stars>
                                    <Rating src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/cce1ebf5-3775-47f1-afc7-07c0113e6147" alt="icon"/>
                                    <_45_0001>
                                        4.5
                                    </_45_0001>
                                </Stars>
                                <Ellipse2/>
                                <_98_0001>
                                    98 оценок
                                </_98_0001>
                            </Frame113>
                            <AccordionExpandIcon_0001>
                                <IconButton src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/e84554d6-92d2-4420-b56c-e607e5eeb509" alt="icon"/>
                            </AccordionExpandIcon_0001>
                        </Container_0002>
                    </AccordionSummary>
                    <DividerContainer>
                        <DividerHorizontal>
                            <MinHeight/>
                            <Divider/>
                        </DividerHorizontal>
                    </DividerContainer>
                </Accordion>
                <Accordion>
                    <AccordionSummary>
                        <Container_0002>
                            <Typography>
                                <Frame114>
                                    <NaN_0044>
                                        Вопросы и Ответы
                                    </NaN_0044>
                                    <_45>
                                        43
                                    </_45>
                                </Frame114>
                            </Typography>
                            <AccordionExpandIcon>
                                <IconButton src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/58066afe-493c-4fc3-afc2-efc49f812a02" alt="icon"/>
                            </AccordionExpandIcon>
                        </Container_0002>
                    </AccordionSummary>
                    <DividerContainer>
                        <DividerHorizontal>
                            <MinHeight/>
                            <Divider/>
                        </DividerHorizontal>
                    </DividerContainer>
                </Accordion>
            </Frame116>
            <Frame18>
                <Title>
                    <NaN_0047>
                        Похожие товары
                    </NaN_0047>
                </Title>
                <Frame18_0001>
                    <Frame16>
                        <ProductCardDesktop>
                            <ImageContainer>
                                <PhotoArea/>
                            </ImageContainer>
                            <TitlePrice>
                                <Price>
                                    <Forester26X40Forester>
                                        Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                    </Forester26X40Forester>
                                </Price>
                                <StarsReviews>
                                    <Stars>
                                        <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6ba23376-64ae-4a9c-9648-2b8cb9529ec7" alt="icon"/>
                                        <_45_0001>
                                            4.5
                                        </_45_0001>
                                    </Stars>
                                    <_98_0002>
                                        98 оценок
                                    </_98_0002>
                                </StarsReviews>
                                <Title_0001>
                                    <_560>
                                        560₽
                                    </_560>
                                </Title_0001>
                            </TitlePrice>
                            <Button_0011>
                                <H6_0012>
                                    В Корзину
                                </H6_0012>
                            </Button_0011>
                        </ProductCardDesktop>
                        <ProductCardDesktop>
                            <ImageContainer>
                                <PhotoArea/>
                            </ImageContainer>
                            <TitlePrice>
                                <Price>
                                    <Forester26X40Forester>
                                        Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                    </Forester26X40Forester>
                                </Price>
                                <StarsReviews>
                                    <Stars>
                                        <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a9dd8673-01a2-4867-ac1e-ed859d4df918" alt="icon"/>
                                        <_45_0001>
                                            4.5
                                        </_45_0001>
                                    </Stars>
                                    <_98_0002>
                                        98 оценок
                                    </_98_0002>
                                </StarsReviews>
                                <Title_0001>
                                    <_560>
                                        560₽
                                    </_560>
                                </Title_0001>
                            </TitlePrice>
                            <Button_0011>
                                <H6_0012>
                                    В Корзину
                                </H6_0012>
                            </Button_0011>
                        </ProductCardDesktop>
                        <ProductCardDesktop>
                            <ImageContainer>
                                <PhotoArea/>
                            </ImageContainer>
                            <TitlePrice>
                                <Price>
                                    <Forester26X40Forester>
                                        Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                    </Forester26X40Forester>
                                </Price>
                                <StarsReviews>
                                    <Stars>
                                        <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/95d24395-89c0-4903-b95f-7b034c41070b" alt="icon"/>
                                        <_45_0001>
                                            4.5
                                        </_45_0001>
                                    </Stars>
                                    <_98_0002>
                                        98 оценок
                                    </_98_0002>
                                </StarsReviews>
                                <Title_0001>
                                    <_560>
                                        560₽
                                    </_560>
                                </Title_0001>
                            </TitlePrice>
                            <Button_0011>
                                <H6_0012>
                                    В Корзину
                                </H6_0012>
                            </Button_0011>
                        </ProductCardDesktop>
                        <ProductCardDesktop>
                            <ImageContainer>
                                <PhotoArea/>
                            </ImageContainer>
                            <TitlePrice>
                                <Price>
                                    <Forester26X40Forester>
                                        Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                    </Forester26X40Forester>
                                </Price>
                                <StarsReviews>
                                    <Stars>
                                        <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a3863067-1b48-4656-8686-a27e46f35a5c" alt="icon"/>
                                        <_45_0001>
                                            4.5
                                        </_45_0001>
                                    </Stars>
                                    <_98_0002>
                                        98 оценок
                                    </_98_0002>
                                </StarsReviews>
                                <Title_0001>
                                    <_560>
                                        560₽
                                    </_560>
                                </Title_0001>
                            </TitlePrice>
                            <Button_0011>
                                <H6_0012>
                                    В Корзину
                                </H6_0012>
                            </Button_0011>
                        </ProductCardDesktop>
                        <ProductCardDesktop>
                            <ImageContainer>
                                <PhotoArea/>
                            </ImageContainer>
                            <TitlePrice>
                                <Price>
                                    <Forester26X40Forester>
                                        Решетка - гриль FORESTER средняя 26x40 см, Решетка - гриль FORESTER средняя
                                    </Forester26X40Forester>
                                </Price>
                                <StarsReviews>
                                    <Stars>
                                        <Star1 src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a26fa858-4753-440d-92a2-6484cb3f215e" alt="icon"/>
                                        <_45_0001>
                                            4.5
                                        </_45_0001>
                                    </Stars>
                                    <_98_0002>
                                        98 оценок
                                    </_98_0002>
                                </StarsReviews>
                                <Title_0001>
                                    <_560>
                                        560₽
                                    </_560>
                                </Title_0001>
                            </TitlePrice>
                            <Button_0011>
                                <H6_0012>
                                    В Корзину
                                </H6_0012>
                            </Button_0011>
                        </ProductCardDesktop>
                    </Frame16>
                    <Button_0016>
                        <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9a4081b5-2ee8-43dd-a2bd-72624c08b0a1" alt="icon"/>
                    </Button_0016>
                    <Button_0017>
                        <Icon src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/bb31fff5-bfbb-4bf8-84fd-0e21f8a87f7a" alt="icon"/>
                    </Button_0017>
                </Frame18_0001>
            </Frame18>
        </RootWrapperProductPage>
    )
}

const RootWrapperProductPage = styled.div`
	min-height: 100vh;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const NavbarStyle8NavbarLight = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	background: rgb(35, 166, 240);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	position: absolute;
	left: 0px;
	top: 0px;
	width: 1440px;
`;

const Container = styled.div`
	height: 48px;
	overflow: hidden;
	background: rgb(37, 43, 66);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
	align-self: stretch;
	flex-shrink: 0;
`;

const Row = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: flex-start;
	box-sizing: border-box;
	padding: 0px 24px;
	position: absolute;
	left: 0px;
	top: 0px;
	width: 1438px;
`;

const ColMd4 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 10px;
	width: 463px;
	height: 46px;
	box-sizing: border-box;
`;

const Button = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 4px;
	border-radius: 4px;
	height: 30px;
	box-sizing: border-box;
	padding: 2px 12px;
`;

const Icon = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const H6 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	line-height: 22px;
	text-align: center;
`;

const BtnSm20 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 5px;
	border-radius: 5px;
	box-sizing: border-box;
	padding: 10px;
`;

const IcnSettingsIcnXs = styled.img`
	width: 16px;
	height: 16px;
	object-fit: cover;
`;

const H6_0001 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

const ColMd4_0001 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 10px;
	width: 463px;
	box-sizing: border-box;
	padding: 10px;
`;

const NaN_0001 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

const Left = styled.div`
	display: flex;
	justify-content: flex-end;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 8px;
	width: 463px;
	height: 46px;
	box-sizing: border-box;
	padding: 10px;
`;

const Button_0001 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	border-radius: 4px;
	height: 30px;
	box-sizing: border-box;
	padding: 2px 4px;
`;

const Frame15 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	gap: 16px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 16px 0px;
	flex-shrink: 0;
`;

const _4 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	gap: 24px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 0px 38px;
	flex-shrink: 0;
`;

const Frame13 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 24px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Logo = styled.div`
	width: 220px;
	height: 48px;
	position: relative;
`;

const NaN_0002 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Montserrat, sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 8px;
`;

const InputHeader = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 12px;
	border: solid 1px rgb(230, 230, 230);
	border-radius: 5px;
	width: 944px;
	height: 48px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
`;

const Button_0002 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	background: rgb(235, 235, 235);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 0px 8px;
	flex-shrink: 0;
`;

const H6_0003 = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 13px;
	font-family: Montserrat, sans-serif;
	font-weight: 500;
	text-align: center;
	width: 26px;
`;

const NaN_0003 = styled.span`
	color: rgba(0, 0, 0, 0.6);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: center;
`;

const Frame11 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	box-sizing: border-box;
`;

const Button_0003 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	border-radius: 4px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 2px 12px;
	flex-shrink: 0;
`;

const H6_0004 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	text-align: center;
`;

const Button_0004 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	border-radius: 4px;
	box-sizing: border-box;
	padding: 2px 12px;
`;

const Badge = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	border-radius: 100px;
	background: rgb(255, 0, 0);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 0px 7px;
`;

const Text = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	line-height: 20px;
	text-align: left;
`;

const _2 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 24px;
	align-self: stretch;
	box-sizing: border-box;
	padding: 0px 40px;
	flex-shrink: 0;
`;

const Button_0005 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 4px;
	border-radius: 4px;
	height: 42px;
	background: linear-gradient(-90deg, rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.2));
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 10px 12px;
`;

const H6_0006 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 22px;
	text-align: center;
`;

const Frame14 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 28px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Tab = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	height: 42px;
	box-sizing: border-box;
	padding: 1px 8px;
`;

const Text_0001 = styled.span`
	color: rgba(255, 255, 255, 0.95);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 500;
	line-height: 22px;
	text-align: left;
`;

const Row_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	gap: 24px;
	background: rgb(42, 124, 199);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 30px 60px 0px;
	position: absolute;
	left: calc((calc((50% + 0px)) - 720px));
	bottom: 0px;
	width: 1440px;
`;

const Frame197 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 8px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const ColMd3 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame198 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 8px;
	box-sizing: border-box;
`;

const NaN_0004 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Montserrat, sans-serif;
	font-weight: 800;
	text-align: left;
`;

const Paragraph = styled.span`
	color: rgba(255, 255, 255, 0.7);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

const SocialMedia = styled.div`
	display: flex;
	justify-content: flex-end;
	flex-direction: row;
	align-items: center;
	flex: 1;
	gap: 20px;
	width: 1057px;
	box-sizing: border-box;
`;

const Facebook = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Instagram = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Twitter = styled.div`
	width: 24px;
	height: 20px;
	overflow: hidden;
	position: relative;
`;

const AntDesignTwitterOutlined = styled.div`
	width: 24px;
	height: 20px;
	overflow: hidden;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Vector = styled.svg`
	width: 22px;
	height: 18px;
	position: absolute;
	left: 2px;
	top: 1px;
	right: 1px;
	bottom: 1px;
`;

const Frame195 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 50px;
	box-sizing: border-box;
`;

const ScheduleFill0Wght300Grad0Opsz2411 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const _90020009001700 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	text-align: center;
`;

const BtnSm20_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	border-radius: 5px;
	box-sizing: border-box;
`;

const CallFill0Wght300Grad0Opsz241 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Info = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	border-radius: 4px;
	box-sizing: border-box;
	padding: 2px 0px;
`;

const MailFill0Wght300Grad0Opsz241 = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Container_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	width: 1050px;
	box-sizing: border-box;
	padding: 25px 0px;
`;

const Row_0002 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 213px;
	box-sizing: border-box;
`;

const ColMd6 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	width: 513px;
	box-sizing: border-box;
`;

const _20062023 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 24px;
	text-align: left;
`;

const Breadcrumb = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	box-sizing: border-box;
	position: absolute;
	left: 60px;
	top: 206px;
`;

const _1StItem = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	box-sizing: border-box;
`;

const _1StItemLabel = styled.span`
	color: rgba(0, 0, 0, 0.45);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 22px;
	text-align: left;
`;

const ComponentsSeparator = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 10px;
	box-sizing: border-box;
	padding: 0px 8px;
`;

const Separator = styled.span`
	color: rgba(0, 0, 0, 0.45);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 22px;
	text-align: left;
`;

const _2NdItem = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
`;

const _2NdItem_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	box-sizing: border-box;
`;

const _2NdItemLabel = styled.span`
	color: rgba(0, 0, 0, 0.45);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 22px;
	text-align: left;
`;

const _2NdToLastItem = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
`;

const _2NdToLastItem_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	box-sizing: border-box;
`;

const _2NdToLastItemLabel = styled.span`
	color: rgba(0, 0, 0, 0.45);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 22px;
	text-align: left;
`;

const LastItem = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
`;

const LastItem_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	box-sizing: border-box;
`;

const LastItemLabel = styled.span`
	color: rgba(0, 0, 0, 0.45);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 22px;
	text-align: left;
`;

const LastItemLabel_0001 = styled.span`
	color: rgba(0, 0, 0, 0.85);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 22px;
	text-align: left;
`;

const TitleImage = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 8px;
	box-sizing: border-box;
	position: absolute;
	left: 242px;
	top: 266px;
`;

const DaewooDwh51373450 = styled.span`
	color: rgba(0, 0, 0, 0.85);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	text-align: left;
`;

const Frame101 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 12px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Stars = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 4px;
	box-sizing: border-box;
`;

const Rating = styled.img`
	width: 18px;
	height: 18px;
	object-fit: cover;
`;

const _45 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Rectangle3 = styled.div`
	width: 1px;
	height: 10px;
	background: linear-gradient(-90deg, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2));
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 2px;
`;

const Articul = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 4px;
	box-sizing: border-box;
`;

const NaN_0005 = styled.span`
	color: rgba(0, 0, 0, 0.7);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const ImagePreview = styled.div`
	width: 528px;
	height: 528px;
	position: relative;
`;

const Image26 = styled.div`
	background: url(https://s3-alpha-sig.figma.com/img/53ac/9091/eb7bd0bcfc1c6956b4c218679ee98151?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Jijrpw0KTnflACzni~fXcbJZyAS~EUvgfMQ-kuGMnR-BkTXsOjZoNvJTx2JH~czJ0nHciIun7qAshxZzJ4Ps~GRgXoJtbNU4p6zBDGajzqnixt1A2yuxneodtN7e7A-dagcl0z6AurhLIMdL-tQE~KHkBH7cLT16wtWoiViMZAZS3eJ1ks3tHVAuOUnooT7~uOljCijun0TZEG4Xxf2LoShjRNhlcJzceSmuudfBBwe2xVc-TbroO36uQAEHXatz-~2ifYdEaP884IQEsbEmHGhkof0icHcjLrCNc1RETfZ1cfvanbvFoC16zU2ty3xkbdmD-R5Q0dTcL6suJcgqjw__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Images = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	gap: 2px;
	box-sizing: border-box;
	position: absolute;
	left: 60px;
	top: 266px;
	height: 586px;
`;

const Images_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: 1;
	gap: 4px;
	height: 534px;
	box-sizing: border-box;
`;

const Image = styled.div`
	width: 92px;
	height: 92px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/53ac/9091/eb7bd0bcfc1c6956b4c218679ee98151?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Jijrpw0KTnflACzni~fXcbJZyAS~EUvgfMQ-kuGMnR-BkTXsOjZoNvJTx2JH~czJ0nHciIun7qAshxZzJ4Ps~GRgXoJtbNU4p6zBDGajzqnixt1A2yuxneodtN7e7A-dagcl0z6AurhLIMdL-tQE~KHkBH7cLT16wtWoiViMZAZS3eJ1ks3tHVAuOUnooT7~uOljCijun0TZEG4Xxf2LoShjRNhlcJzceSmuudfBBwe2xVc-TbroO36uQAEHXatz-~2ifYdEaP884IQEsbEmHGhkof0icHcjLrCNc1RETfZ1cfvanbvFoC16zU2ty3xkbdmD-R5Q0dTcL6suJcgqjw__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border: solid 2px rgb(35, 166, 240);
	border-radius: 6px;
	position: relative;
`;

const Image_0001 = styled.div`
	width: 92px;
	height: 92px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/d998/0602/4796f9f991e527f3cc5c43fe1ff83d35?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=UOQxUg64VijHb1FZVMvPKW2Tlf90Q09sh1bMhiDD4-nUiDsB8phnhfzTAg1CDdsehs-U9rq9eEKH4KX~4ATFQ7iv5StVY8mCpbD3GdxLCoBW1~rC0WYd3RAkRsf~kAnS0q~BmyO5HlP7U9~v4asVusQdN-uF8Y28ZHvWsuQggI5LrRi~Mw3iiikrLudTt9XrPrDdhoVZ-5J0xsVH8CH8F1RYxTp3JU4KnHmphXKDz3NDV17ZL8ZULtavRRWu4slKOy83Ruzc5WDdGiWM8W21bNEw~BHvv-T5Eo6wwuzLQrmIxVylzAXWgj5jQ3DpKHlmx7fwzvaWADbAlN4DvHFLYw__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border: solid 1px rgba(0, 0, 0, 0.04);
	border-radius: 6px;
	position: relative;
`;

const Image_0002 = styled.div`
	width: 92px;
	height: 92px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/fc1e/1296/5f4fad9732eddbfe8f644ca80966cc56?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=Dqd1yUTi4celSqyNHdfZluwhbfAp6EmFsV6GvzYYA14mfNM0IpKV6Hw1jIDeZMiFudn0tWjC3vdkBo5tzkp-JJYInxpr0n99dARFK2TCc4JHgrzp1zGGMgOrMm1YqJCdg~agkJsMv~35C89fmns6P1F1YtXvcsD-T2r3rXy~3wWjNHDTIvq0DrlWDfGYbCDhHvVVh-s12AhjQk7Ut1zQmhD96a3juiTtCR-x~4I-VBJen~gPXhQYNB74r7RUxDOXkKYRKjnXs1CpMZ4o7dBmOcl6S5xFj2ub2hA24SLm4kPQLiiMcs84SX2-gLLz-AINoKy~n5MvW8ijENWGq-iQGA__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border: solid 1px rgba(0, 0, 0, 0.04);
	border-radius: 6px;
	position: relative;
`;

const Image_0003 = styled.div`
	width: 92px;
	height: 92px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/c100/d1ec/b3899b158edd39adf34673d519fdff7e?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=kE-1Iy43qZhW6MDM8eEezkMNb-HlGcgK54h~v82JxEzZY0FstU24T4jSejXps-JopPxjJHeYX63gfkwt4y0DDt6G83oy0rjra4tvUR9XGJ-B1XCx0oKVCg0t89afqfVtWe~Tv6F6ky9YYOV2FMJ0Z8eL-1Nc2yx9nhOvAaBB2E2O9gYfWZJtFGW0gJL1Yb6aCT0eswOHXp6FABdIwDrI2w5VZNdMQQzq9Tju76Fu5SIo7MYn6ifkFT6twZVoVFaBqSdhwEwK7dgc0yNTJHiPjBXG~G8YTwVPiw~bjXA0hJKcSR2VX3OTlKNg2qBPZigSZdc3Guf3RYVO7NMSYj4V9A__);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	border: solid 1px rgba(0, 0, 0, 0.04);
	border-radius: 6px;
	position: relative;
`;

const RightInfo = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 25px;
	box-sizing: border-box;
	position: absolute;
	left: 844px;
	top: 266px;
`;

const PriceAddToBag = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 20px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame105 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	box-sizing: border-box;
`;

const _12990 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 28px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	text-align: left;
`;

const NaN_0006 = styled.span`
	color: rgb(54, 163, 59);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	line-height: 22px;
	text-align: center;
`;

const ShippingSettings = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 8px;
	width: 334px;
	box-sizing: border-box;
`;

const NaN_0007 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
	align-self: stretch;
	flex-shrink: 0;
`;

const Cards = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 8px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Card = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 8px;
	border: solid 1px rgba(0, 0, 0, 0.05);
	border-radius: 6px;
	align-self: stretch;
	background: rgb(252, 252, 252);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 8px;
	flex-shrink: 0;
`;

const Frame = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Frame151 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	flex: 1;
	gap: 2px;
	width: 254px;
	box-sizing: border-box;
`;

const NaN_0008 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	text-align: left;
	align-self: stretch;
	flex-shrink: 0;
`;

const _34 = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: center;
`;

const Button_0006 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 4px;
	border-radius: 4px;
	box-sizing: border-box;
	padding: 2px 4px;
`;

const Icon_0008 = styled.img`
	width: 16px;
	height: 16px;
	object-fit: cover;
`;

const NaN_0009 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	text-align: center;
`;

const NaN_0010 = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: center;
`;

const Add = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;

const Frame103 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 6px;
	box-sizing: border-box;
`;

const Button_0007 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	border: solid 1px rgba(0, 0, 0, 0.1);
	border-radius: 4px;
	width: 42px;
	height: 42px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 10px 20px;
	opacity: 0.4;
	transform: rotate(-180deg);
	transform-origin: top left;
`;

const Frame102 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 4px;
	border: solid 1px rgb(121, 116, 126);
	border-radius: 4px;
	width: 58px;
	height: 42px;
	box-sizing: border-box;
	padding: 4px;
`;

const _1 = styled.span`
	color: rgb(73, 69, 79);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	letter-spacing: 1px;
	line-height: 24px;
	text-align: left;
`;

const Button_0008 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	border: solid 1px rgba(0, 0, 0, 0.1);
	border-radius: 4px;
	width: 42px;
	height: 42px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 10px 20px;
	transform: rotate(-180deg);
	transform-origin: top left;
`;

const Button_0009 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 10px;
	border-radius: 4px;
	width: 334px;
	background: rgb(35, 166, 240);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 14px 12px;
`;

const H6_0010 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 18px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	line-height: 22px;
	text-align: center;
`;

const KeyValue = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 8px;
	box-sizing: border-box;
`;

const NaN_0011 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 16px;
	width: 536px;
	box-sizing: border-box;
`;

const NaN_0012 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	line-height: 22px;
	text-align: center;
`;

const Infos = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 4px;
	width: 536px;
	box-sizing: border-box;
`;

const InfoItems = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 12px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
	opacity: 0.8;
`;

const NaN_0014 = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 22px;
	text-align: center;
`;

const Lier = styled.img`
	width: 294px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const _30 = styled.span`
	color: rgba(0, 0, 0, 0.9);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	line-height: 22px;
	text-align: center;
`;

const InfoItems_0001 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 12px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Lier_0001 = styled.img`
	width: 414px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const NaN_0016 = styled.span`
	color: rgba(0, 0, 0, 0.9);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	line-height: 22px;
	text-align: center;
`;

const Lier_0002 = styled.img`
	width: 166px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const Lier_0003 = styled.img`
	width: 186px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const Vector1 = styled.img`
	width: 215px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const Lier_0005 = styled.img`
	width: 215px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const _50 = styled.span`
	color: rgba(0, 0, 0, 0.9);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	line-height: 22px;
	text-align: center;
`;

const Button_0010 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 10px;
	border-radius: 4px;
	height: 26px;
	box-sizing: border-box;
	padding: 2px 4px;
`;

const H6_0011 = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 600;
	line-height: 22px;
	text-align: center;
	text-decoration: underline;
`;

const Frame108 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 24px;
	box-sizing: border-box;
	padding: 0px 60px;
	position: absolute;
	left: 0px;
	top: 910px;
	width: 1440px;
`;

const NaN_0021 = styled.span`
	color: rgba(0, 0, 0, 0.85);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	text-align: left;
`;

const AboutSection = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
`;

const AboutSection_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	width: 955px;
	box-sizing: border-box;
`;

const KronostarGalaxy = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 975px;
`;

const Frame107 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 24px;
	box-sizing: border-box;
`;

const NaN_0024 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 22px;
	text-align: center;
`;

const Lier_0006 = styled.img`
	width: 293px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const _30_0001 = styled.span`
	color: rgba(0, 0, 0, 0.9);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	line-height: 22px;
	text-align: center;
`;

const Lier_0007 = styled.img`
	width: 413px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const Lier_0008 = styled.img`
	width: 163px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const _1060_0001 = styled.span`
	color: rgba(0, 0, 0, 0.9);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 500;
	line-height: 22px;
	text-align: center;
`;

const Lier_0009 = styled.img`
	width: 185px;
	height: 0px;
	object-fit: cover;
	flex: 1;
`;

const InfoItems_0014 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 12px;
	align-self: stretch;
	height: 23px;
	box-sizing: border-box;
	flex-shrink: 0;
	opacity: 0.8;
`;

const Frame116 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 12px;
	box-sizing: border-box;
	position: absolute;
	left: 60px;
	top: 1611px;
`;

const Accordion = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	width: 1320px;
	box-sizing: border-box;
`;

const AccordionSummary = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	box-shadow: 0px 1px 3px  rgba(0, 0, 0, 0.12),0px 1px 1px  rgba(0, 0, 0, 0.14),0px 2px 1px -1px rgba(0, 0, 0, 0.2);
	align-self: stretch;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Container_0002 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	box-sizing: border-box;
	padding: 0px 16px;
	flex-shrink: 0;
`;

const Typography = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: 1;
	width: 644px;
	height: 24px;
	box-sizing: border-box;
`;

const NaN_0044 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 22px;
	text-align: left;
`;

const AccordionExpandIcon = styled.div`
	display: flex;
	justify-content: flex-end;
	flex-direction: row;
	align-items: center;
	flex: 1;
	width: 644px;
	box-sizing: border-box;
`;

const IconButton = styled.img`
	width: 40px;
	height: 40px;
	object-fit: cover;
`;

const DividerContainer = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	align-self: stretch;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const DividerHorizontal = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const MinHeight = styled.div`
	width: 0px;
	height: 1px;
	overflow: hidden;
	position: relative;
`;

const Divider = styled.div`
	height: 0px;
	border-top: solid 1px rgba(0, 0, 0, 0.12);
	align-self: stretch;
	flex-shrink: 0;
`;

const Typography_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	height: 24px;
	box-sizing: border-box;
	padding-right: 40px;
`;

const Frame114 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 4px;
	box-sizing: border-box;
`;

const Frame113 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 8px;
	box-sizing: border-box;
`;

const _45_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Ellipse2 = styled.div`
	width: 4px;
	height: 4px;
	background: linear-gradient(-90deg, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2));
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	border-radius: 4px / 4px;
`;

const _98_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const AccordionExpandIcon_0001 = styled.div`
	display: flex;
	justify-content: flex-end;
	flex-direction: row;
	align-items: center;
	flex: 1;
	width: 1035px;
	box-sizing: border-box;
`;

const Frame18 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 16px;
	box-sizing: border-box;
	padding: 0px 60px;
	position: absolute;
	left: 0px;
	top: 1905px;
	width: 1440px;
`;

const Title = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	height: 42px;
	box-sizing: border-box;
	padding: 10px;
	flex-shrink: 0;
`;

const NaN_0047 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Montserrat, sans-serif;
	font-weight: 700;
	line-height: 22px;
	text-align: center;
`;

const Frame18_0001 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: center;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Frame16 = styled.div`
	display: flex;
	justify-content: space-between;
	flex-direction: row;
	align-items: flex-start;
	flex: 1;
	width: 1320px;
	box-sizing: border-box;
`;

const ProductCardDesktop = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 8px;
	border-radius: 6px;
	width: 240px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 20px;
`;

const ImageContainer = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	height: 200px;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const PhotoArea = styled.div`
	width: 188px;
	height: 188px;
	overflow: hidden;
	background: url(https://s3-alpha-sig.figma.com/img/66c4/4fd1/243b1f5431c096e58e57aa8ec38dae7a?Expires=1707091200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=F6mugLHvCeVJ817NJEoCYep7PAFD~f5jk1SGzaAyMLbSoLPIYS80su9z~4FeeOOGC6iTFJVxToougdz8B7-igHUl9DFboToAtiD9Z2onkcOGqtXP3YTEIYKeTjy4TwQZtmuTo444k6FgteO3O34L4y~AoslDYxLeTVik7JsTptXd0YpBF3GXYXq1hMMdnsPyPIej4m1-m~1yGE7csdVugI-irSJs0ijpgus80iUEdQn9kGm4wIuH4TLtBHYLrdfkwy4DNOxbVbfwL3T0SgZwd4KXBI0Rv3gFTIKgBWD08Pf6wdW8UWY1GQipM42jgXeSz16JmPtBiwEXjrF9PvWKOA__);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	position: relative;
`;

const TitlePrice = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 4px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Price = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Forester26X40Forester = styled.span`
	color: rgba(0, 0, 0, 0.8);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
	width: 200px;
	flex: 1;
`;

const StarsReviews = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 8px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const Star1 = styled.img`
	width: 18px;
	height: 18px;
	object-fit: cover;
`;

const _98_0002 = styled.span`
	color: rgba(0, 0, 0, 0.7);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	text-align: left;
`;

const Title_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 10px;
	align-self: stretch;
	box-sizing: border-box;
	flex-shrink: 0;
`;

const _560 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	text-align: left;
`;

const Button_0011 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	border-radius: 4px;
	height: 42px;
	background: rgb(35, 166, 240);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 10px 12px;
	opacity: 0;
`;

const H6_0012 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	line-height: 22px;
	text-align: center;
`;

const Button_0016 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: flex-start;
	flex: none;
	gap: 10px;
	box-shadow: 0px 1px 2px  rgba(0, 0, 0, 0.3),0px 1px 3px 1px rgba(0, 0, 0, 0.15);
	border-radius: 54px;
	width: 42px;
	height: 42px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
	padding: 10px 20px;
	transform: rotate(-180deg);
	transform-origin: top left;
`;

const Button_0017 = styled.div`
	display: flex;
	justify-content: center;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 10px;
	box-shadow: 0px 1px 2px  rgba(0, 0, 0, 0.3),0px 1px 3px 1px rgba(0, 0, 0, 0.15);
	border-radius: 54px;
	width: 42px;
	height: 42px;
	background: rgb(255, 255, 255);
	background-repeat: no-repeat;
	background-size: contain;
	background-position: center;
	box-sizing: border-box;
`;

